### ISSUE TITLE
macOS notarization failing in cryptic ways

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#107]
[Link to GHA log line](https://github.com/paneron/paneron/actions/runs/6157305152/job/16723749005#step:8:1841). @CAMOBAP, @ribose-jeffreylau  could you take a look when you have time? Is it the usual contract change issue or something new?

**Comment by CAMOBAP** [comment]
Something goes wrong during signing of macOS app, and it looks stable (5 out of 5 attempts)

We definitely have to try to uploading `notarization-error.log` on failures on Macos

**Comment by ronaldtse** [comment]
@CAMOBAP I've accepted the new agreement on the developer portal. See if it works now?

**Comment by strogonoff** [comment]
I rerun the jobs. Alex had to step away for 30 min or so.

**Comment by strogonoff** [comment]
@CAMOBAP 

 > Something goes wrong during signing of macOS app, and it looks stable (5 out of 5 attempts)

Yeah. That much I could say. 

> We definitely have to try to uploading `notarization-error.log` on failures on Macos

Upload where? You mean as an artifact? That would be a welcome change (filed #109).

Can we just display these errors in GHA console? We used to get contract-related error information directly in console output, but not anymore after CI refactor. Now there are no details, just “notarization failed”. I wonder why—I don’t think any sensitive information is revealed in that error message, and having review .log files is an inconvenience. Since contracts are changed periodically, these errors will keep happening.

**Comment by ronaldtse** [comment]
@strogonoff are the jobs fixed?

**Comment by strogonoff** [comment]
Yes!
