### ISSUE TITLE
Datasets: reading objects on Windows system may not be constructing absolute object paths correctly

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#110]
@CAMOBAP, if you happen to have the `main.log` file we have looked during the call, could you attach it to this ticket?

**Comment by CAMOBAP** [comment]
✅  [paneron_sync_error.log](https://github.com/paneron/paneron/files/12594855/paneron_sync_error.log)

**Comment by strogonoff** [comment]
It starts to look suspiciously like it’s the POSIX path separator issue coming back to bite yet again.

`getDatasetRoot(repoDir, datasetID)` can in fact be called with an empty string for `repoDir`, and doesn’t have to return an absolute filesystem path to dataset, so that’s not where the problem is.

However, it seems like object paths that are passed to `git.readBlob()` (which is used when we are fetching object
 data _at particular version_—@CAMOBAP, you asked whether we read objects from filesystem or from Git store; in case where) are constructed with Node’s `path.join()`. Which of course uses `\` as separator on Windows.

**Comment by strogonoff** [comment]
(Closed by mistake)

**Comment by strogonoff** [comment]
It starts to look suspiciously like it’s the POSIX path separator issue coming back to bite yet again.

[`getDatasetRoot(repoDir, datasetID)`](https://github.com/paneron/paneron/blob/43533a2cc01d03f23d8ec277ef62a67d80fc545f/src/repositories/main/meta.ts#L62) can in fact be called with an empty string for `repoDir`, and doesn’t have to return an absolute filesystem path to dataset, so that’s not where the problem is.

However, it seems like object paths that are passed to `git.readBlob()`[0] [are constructed with Node’s `path.join()`](https://github.com/paneron/paneron/blob/43533a2cc01d03f23d8ec277ef62a67d80fc545f/src/datasets/main/objects/read.ts#L163-L167). Which might use `\` as separator on Windows, whereas Isomorphic Git’s functions might expect forward-slash-separated object paths on any platform.

[0] @CAMOBAP you asked whether we read files or Git objects. When we diff changes between commits, which is what happens after any change, we do need to read an object (file) at a particular commit, and in that case we do read corresponding blob directly from Git store.

**Comment by strogonoff** [comment]
Fix should be in 2.2.0, draft release should be ready for tests.

**Comment by strogonoff** [comment]
Fixed in 2.2.1, confirmed by @CAMOBAP.
