### ISSUE TITLE
Notarization fails (agreement check)

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#118]
Build error happens during notarisation. <s>It looks like logs are unavailable (#119).</s>

https://github.com/paneron/paneron/actions/runs/7005344337/job/19081172209

**Comment by strogonoff** [comment]
I don’t think we can do much without logs can we?

**Comment by strogonoff** [comment]
Looks like we need to check the agreement:

> Failed to notarize via notarytool

> Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.

**Comment by ribose-jeffreylau** [comment]
Build passes again.  Closing.
