### ISSUE TITLE
Data repositories that are read-only should not be shown as "network error"

### ISSUE THREAD

**Issue by ronaldtse** [paneron/paneron#12]
The repository that says "network error" is due to the repository being read-only, i.e. my account doesn't have write access. We should label it properly such as "read-only access", not "network error".

<img width="497" alt="Screen Shot 2020-11-18 at 10 45 58 AM" src="https://user-images.githubusercontent.com/11865/99476303-3f0de400-298b-11eb-90a0-b0ba1ed13f67.png">

**Comment by strogonoff** [comment]
This works as designed; there is no concept of read-only repositories in Paneron really at this point. The bug is that the app must not allow to add a repository to which there is no push access.

**Comment by strogonoff** [comment]
I can either repurpose this issue, or close and open a new issue about adding repositories without push access.

**Comment by ronaldtse** [comment]
Just repurpose this issue as you see fit. Thanks!

**Comment by strogonoff** [comment]
Proper read-only repository support is in alpha19 now.

When a shared repository is added, Paneron detects if user-provided credentials allow write access, and if not it (1) does not attempt to push (meaning no network error), (2) does not provide object change API to extensions (in absence of which extensions are supposed to display datasets in this repo as read-only, and (3) displays read-only label in repository list.
