### ISSUE TITLE
Issue with adding shared repositories

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#78]
From Jeffrey in an unrelated issue #40:

My work-around is:

```console
> git clone "$REPO_URL" "/Users/$USER/Library/Application Support/Paneron/working_copies/${the_uuid_of_repo}"
```

then reload Paneron.  It'll then sync successfully.

_Originally posted by @ribose-jeffreylau in https://github.com/paneron/paneron/issues/40#issuecomment-1522854297_

**Comment by strogonoff** [comment]
Jeffrey, so it seems like a bug when you add a shared repository?

- Could you describe the condition in GUI when you do this?
- Can you try to remember what changed between the last time and now?
- Can you try Paneron 2.0.2/2.0.1 and see if the same issue persists?

It could be the bug I was having with CI-built Paneron. Interesting, we confirmed that you macOS of the same version and same Paneron version (you downloaded it from CI, like I did) didn’t have the problem.

**Comment by ribose-jeffreylau** [comment]
> * Could you describe the condition in GUI when you do this?

I was on the screen where remote repository details are to be filled in, i.e. the screen where buttons "Test connection" and "Import" are present.
An item titled "(no title)" appears on the left side bar, which, when clicked, stays as "(no title)", and inspector would show the same error message about failing to sync.

> * Can you try to remember what changed between the last time and now?

Can't remember.

> * Can you try Paneron 2.0.2/2.0.1 and see if the same issue persists?

For both 2.0.1 and 2.0.2, after clicking "Import", "(no title)" would appear on the left, and inspector would first show a warning log and then an error log, both displaying the same message regarding failure to sync.  After a few seconds,  "(no title)" would turn into the actual title of the registry.  Subsequent inspector messages would show that the repo would sync, and the error messages never appeared again.

Both would warn about "main" branch not being available.

But no warning in 2.0.3.  This might be the reason "Import" fails and never recovers in 2.0.3.

**Comment by strogonoff** [comment]
> An item titled "(no title)" appears on the left side bar, which, when clicked, stays as "(no title)", and inspector would show the same error message about failing to sync.

If it’s a large repository, it may take a minute to load and update the `(no title)` to actual title🤔 I think an update of UX progress status report is in order.

**Comment by strogonoff** [comment]
> would appear on the left, and inspector would first show a warning log and then an error log, both displaying the same message regarding failure to sync

The message logged to stderr at “error” level, but it doesn’t necessarily reflect an error state. I know it’s suboptimal…

**Comment by strogonoff** [comment]
It looks like the error is different from the one I encountered, which is good I guess. Let me try to reproduce this.

**Comment by ribose-jeffreylau** [comment]
repo: https://github.com/ribose-jeffreylau/isogr-registry

**Comment by ribose-jeffreylau** [comment]
Error in 2.0.3 happened when I left the branch blank.   Repo has no "main" branch, only "master".  My guess is it tries to clone "main" over and over but fails for obvious reasons.

**Comment by ronaldtse** [comment]
I think we ought to support both `main` and `master` at this point.

**Comment by strogonoff** [comment]
@ribose-jeffreylau repository import UX should be better in 2.0.4 (when [this build](https://github.com/paneron/paneron/actions/runs/4839680814) succeeds). It will now 1) check that requested branch exists on remote; 2) show “loading” while the cloning is ongoing and fail immediately if any error occurs.
