### ISSUE TITLE
Update macOS notarization flow by 2023-11-01 from `altool` to `notarytool`

### ISSUE THREAD

**Issue by ronaldtse** [paneron/paneron#82]
From Apple Developer Relations:

We’re reaching out because you recently used the altool command-line utility to notarize your macOS software with Apple. As announced last year at WWDC22, if you’re still using altool with the Apple notary service, you should transition to the notarytool command-line utility as soon as possible. Notarizing software with altool was deprecated in Xcode 13, and the Apple notary service will no longer accept uploads from altool as of November 1, 2023. Existing notarized software will continue to function properly.

For information on notarizing your apps, read TechNote TN3147: Migrating to the latest notarization tool. If you have any questions, contact us. 

_Originally posted by @ronaldtse in https://github.com/paneron/paneron/issues/81#issuecomment-1616366192_

**Comment by ribose-jeffreylau** [comment]
According to https://github.com/electron/notarize#notes-on-your-teamid, a`teamId` needs to be set.

**Comment by ronaldtse** [comment]
> According to https://github.com/electron/notarize#notes-on-your-teamid, a`teamId` needs to be set.

Our team ID is XX7DG778PN
