### ISSUE TITLE
Build/release workflow failing with “Resource is busy or locked”

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#94]
https://github.com/paneron/paneron/actions/runs/5472741264/jobs/9965293908#step:9:952

**Comment by ribose-jeffreylau** [comment]
This could be related to some Powershell syntax error during the downloading of metanorma.

**Comment by ribose-jeffreylau** [comment]
Fixed by 98a8500978ec9c4972c5abc64bc912b16ffe5c2b
