### ISSUE TITLE
CI is not building

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#98]
It looks like builds have stopped after commit https://github.com/paneron/paneron/commit/92322c973236d30bcb0b4c82973b61644bbc18fd.

I was a bit eager and reverted a couple more commits back to https://github.com/paneron/paneron/commit/9604207051db71ac67a448059a9d4a23374ee1ea.

The reversion commit is at https://github.com/paneron/paneron/commit/f03c4c08295d810db8f70e0fee440729f3fd1508. It seems to be building something after that, I am monitoring the outcome… (@ribose-jeffreylau you can take that reversion commit and revert it against your copy to try to fix)

**Comment by ribose-jeffreylau** [comment]
Thanks, I'll revert commit and see what went wrong.

**Comment by strogonoff** [comment]
@ribose-jeffreylau this commit is a *reversion of your changes*. You are free to revert it against your local copy but please don’t push until it’s fixed (or until time where we have some idle time for testing CI). I’m going to reset to that reversion and force push…

**Comment by ribose-jeffreylau** [comment]
@strogonoff Thanks for investigating.  I tried the fix on my fork and seemed to work.

**Comment by strogonoff** [comment]
@ribose-jeffreylau Feel free to reapply the change later today, but not right now (there’s another build I need to run). I‘d appreciate if 1) it was a single commit, so we can revert it easily if things go wrong and 2) we’d need to make sure build artifacts get uploaded to latest release draft

**Comment by strogonoff** [comment]
Unfortunately, it looks like it’s not building… Since we need builds to happen right now, I am reverting the last two CI-related commits to try to get to working state. (Done in 3b3f077.)

**Comment by strogonoff** [comment]
One problem is due to insufficient timeout (it was reduced from 120000 to 12000), another problem is I’m not sure what. I’d recommend to make a PR for CI changes and ask @CAMOBAP to review, he’s fairly deep into GHA/CI I think…

**Comment by strogonoff** [comment]
@CAMOBAP I know that a refactor is pending in a PR, but there is this bug again with Windows build, “resource busy or locked”: https://github.com/paneron/paneron/actions/runs/5782392990/job/15669119042#step:9:952

Do you reckon a fix is easy to implement while PR is coming?🤔

If it’s something in a third-party action we can’t fix right away, we can merge the PR and see if it’s fixed then.

cc @ribose-jeffreylau

**Comment by ribose-jeffreylau** [comment]
More attempts usually "fixes" the issue.  The refactor PR introduces a (configurable) 5-attempt retry to the build process.

**Comment by strogonoff** [comment]
Got it. I see that it works now. If you retried the build, thank you🙏

**Comment by ronaldtse** [comment]
@strogonoff please close this issue if the CI builds, thanks.

**Comment by strogonoff** [comment]
@ronaldtse CI issue is not fixed until we are done with @ribose-jeffreylau’s refactor at https://github.com/paneron/paneron/pull/99.

**Comment by strogonoff** [comment]
Actually, the issue refers to the case when that refactor was pushed before it’s ready and broke the build. Since that refactor was since then reverted, we can consider it fixed and have another issue for build refactor.
